\copy customers FROM 'data/olist_customers_dataset.csv' CSV HEADER ENCODING 'UTF8';
\copy geolocation FROM 'data/olist_geolocation_dataset.csv' CSV HEADER ENCODING 'UTF8';
\copy sellers FROM 'data/olist_sellers_dataset.csv' CSV HEADER ENCODING 'UTF8';
\copy products FROM 'data/olist_products_dataset.csv' CSV HEADER ENCODING 'UTF8';
\copy product_category_name_translation FROM 'data/product_category_name_translation.csv' CSV HEADER ENCODING 'UTF8';
\copy orders FROM 'data/olist_orders_dataset.csv' CSV HEADER ENCODING 'UTF8';
\copy order_items FROM 'data/olist_order_items_dataset.csv' CSV HEADER ENCODING 'UTF8';
\copy order_payments FROM 'data/olist_order_payments_dataset.csv' CSV HEADER ENCODING 'UTF8';
\copy order_reviews FROM 'data/olist_order_reviews_dataset.csv' CSV HEADER ENCODING 'UTF8';
